### ISSUE TITLE
First class Debian package support

### ISSUE THREAD

**Issue by mattyjones** [influxdata/kapacitor#1055]
I was looking at creating first class support for both kapacitor and telegraf for Debain. Are there thoughts on this here? There is currently no official packages for Debian and I am running tlegraf on it, in a production capacity and would like support for it.

**Comment by rossmcdonald** [comment]
We recommend using the [InfluxData package repository](https://www.influxdata.com/package-repository-for-linux/) whenever possible, since it is kept up-to-date and is integrated into our release pipeline. You are more than welcome to create official packages for Debian, though, if you have the time and expertise. Kapacitor and Telegraf both have pretty fast release cycles right now, so I think keeping them up-to-date will be the biggest challenge.

You might also want to reach out to the maintainers of the [current InfluxDB Debian package](https://packages.debian.org/sid/influxdb) to see what their thoughts are.
