### ISSUE TITLE
Expression to check if a tag exists

### ISSUE THREAD

**Issue by m4ce** [influxdata/kapacitor#1075]
Hi,

I know you can build conditions like: {{ if ne .Level "CRITICAL" }} .. {{ else }} .. {{ end }}

How to check if a specific tag or field exists?

Also, is there any specific documentation I should refer to regarding this templating syntax?

Thank you for your help.

**Comment by nathanielc** [comment]
For docs on the template engine see https://golang.org/pkg/text/template/

There is no method to check if the field exists, you have to compare against a value of the field or tag. The [DefaultNode](https://docs.influxdata.com/kapacitor/v1.1/nodes/default_node/) is useful here, since it can set a value if the field or tag doesn't exist.

**Comment by m4ce** [comment]
@nathanielc, thanks for the tip about DefaultNode. I think I can take it from there now.
