### ISSUE TITLE
Derivative computation is shifted

### ISSUE THREAD

**Issue by melck** [influxdata/kapacitor#111]
I have tried to compute cpu usage from scratch. I use derivative's function, but the results are shifted in comparison of telegraf's computation.

Tick script 
```go
var guest = stream
    .from().measurement('cpu_time_guest')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var guest_nice = stream
    .from().measurement('cpu_time_guest_nice')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var idle = stream
    .from().measurement('cpu_time_idle')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var iowait = stream
    .from().measurement('cpu_time_iowait')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var irq = stream
    .from().measurement('cpu_time_irq')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var nice = stream
    .from().measurement('cpu_time_nice')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var softirq = stream
    .from().measurement('cpu_time_softirq')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var steal = stream
    .from().measurement('cpu_time_steal')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var system = stream
    .from().measurement('cpu_time_system')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var user = stream
    .from().measurement('cpu_time_user')
    .where(lambda: "cpu" == 'cpu-total')
    .groupBy('host')
    .derivative('value')
      .unit(10s)
      .nonNegative()

var percent = guest
    .join(guest_nice, idle, iowait, irq, nice, softirq, steal, system, user)
        .as('guest', 'guest_nice', 'idle', 'iowait', 'irq', 'nice', 'softirq', 'steal', 'system', 'user')
    .eval(lambda: float(100) * ("user.value" / ("guest.value" + "guest_nice.value" + "idle.value" + "iowait.value" + "irq.value" + "nice.value" + "softirq.value" + "steal.value" + "system.value" + "user.value")))
        .as('value')
        .keep('host', 'value')
    .influxDBOut()
        .database('telegraf')
        .measurement('_temp')
```

Graph results:
![image](https://cloud.githubusercontent.com/assets/813889/11951408/f4838a96-a890-11e5-8d6f-4f206b12af59.png)

**Comment by nathanielc** [comment]
By how much is it shifted? From what I can see on the graph it looks to be shifted by about 10s, is that right? This could be because of how the derivative is calculated left hand or right handed. For example, given the following data:

```
cpu_time_guest value=1000 1450790000
cpu_time_guest value=1002 1450790001
cpu_time_guest value=1004 1450790002
cpu_time_guest value=1006 1450790003
cpu_time_guest value=1008 1450790004
```

The derivative could be calculated one of two ways:

Using first timestamp
```
dcpu_time_guest value=2 1450790000
dcpu_time_guest value=2 1450790001
dcpu_time_guest value=2 1450790002
dcpu_time_guest value=2 1450790003
```

Using last timestamp

```
dcpu_time_guest value=2 1450790001
dcpu_time_guest value=2 1450790002
dcpu_time_guest value=2 1450790003
dcpu_time_guest value=2 1450790004
```

Kapacitor uses the first timestamp. What is your use case? Does the time shift from using the first timestamp affect your overall result? It makes sense that it should probably be the same as Telegraf so that they line up but I would like to understand your use case a bit better.

Thanks for the detailed report.

**Comment by melck** [comment]
I wanted to understand tick script and manipulate stream. To do that, I choose to start by a reproduction of cpu usage metrics. I was wondering why time was shifted from one tick. Thanks for the explanation. Is there way to choose derivative "right handed" ? 

My original goal was to calculate procstats cpu metrics from telegraf in percentage. But i'm a little stuck for now.

**Comment by nathanielc** [comment]
@melck  There is no option to make the derivative `right handed`. I choose left handed because it makes it easier to reason about windows later on since the start of the window is the start of the data set instead of dropping the first timestamp. Its not a big deal and could be changed to right handed or maybe turned into an option if we found a strong use case.

Something that you do bring up though is it would be nice to explicitly shift values in time, since that has a much wider usefulness and would also solve your issue.

Something like this would be trivial to implement:

```
stream.from()...
   .timeShift(10s)
```
or 

```
stream.from()...
   .timeShift(-10s)
```

**Comment by melck** [comment]
@nathanielc I understand and i also prefer shift values in time. It will may be usefull for other cases.

**Comment by nathanielc** [comment]
Shift has been implemented
