### ISSUE TITLE
Augment the event Buffer size

### ISSUE THREAD

**Issue by ellis2323** [influxdata/kapacitor#1131]
Hello,

I'm using telegraf to monitor snmp routers/switches/optical equipments. Currently it is more than 700 equipments. We use kapacitor in stream node to check pings with sensu as alerting system. 

To make it works, i had pushed the limit of eventBufferSize from 100 to 5000. Not sure, i need so many events but the limit to 100 seems a little conservative.

The constant value is defined in alert/topics.go line 16.

Best regards

**Comment by nathanielc** [comment]
@ellis2323 Thanks for letting us know.  The event buffer/topic features a brand new. Can you share more details about what behavior you were seeing before and after increasing the eventBufferSize? How many events per second are you generating?  etc...

**Comment by ellis2323** [comment]
I had many error messages from the file services/alert/handlers.go
```
return fmt.Errorf("failed to deliver event %q to handler", event.State.ID)
```
I have actually 700 equipments i monitored with telegraf. In this case, i check ping response. Telegraf seems to check all equipments in the same second.

**Comment by pommi** [comment]
Hi,

We've been having this issue as well and waited for v1.4.0 to fix this in our setup. Yesterday we rolled out this version, but unfortunately we still get an insane amount of these errors:
```
ts=2017-12-14T12:49:15.145Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=critical_logs node=alert3 err="failed to deliver event \"mendix_runtime.critical_logs_count:app_name=03f98f2a-603c-41ce-bc43-16d73db53787\" to handler"
ts=2017-12-14T12:49:15.145Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=critical_logs node=alert3 err="failed to deliver event \"mendix_runtime.critical_logs_count:app_name=0ee02ca5-193c-43d9-af46-8a7d48a41b04\" to handler"
ts=2017-12-14T12:49:15.941Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=critical_logs node=alert3 err="failed to deliver event \"mendix_runtime.critical_logs_count:app_name=5691b627-b0e1-46e0-932e-c2781b44d6c4\" to handler"
ts=2017-12-14T12:49:15.955Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=critical_logs node=alert3 err="failed to deliver event \"mendix_runtime.critical_logs_count:app_name=e879adc2-8ab2-4a97-8699-230f0213900b\" to handler"
ts=2017-12-14T12:49:15.956Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=critical_logs node=alert3 err="failed to deliver event \"mendix_runtime.critical_logs_count:app_name=754f322d-a328-4d1a-8174-a4dcaff890b8\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
ts=2017-12-14T12:49:28.957Z lvl=error msg="encountered error collecting event" service=kapacitor task_master=main task=runtime_heartbeat node=alert3 err="failed to deliver event \":nil\" to handler"
```

Some info about our setup:
* Kapacitor is subscribed to an InfluxDB instance at InfluxCloud
* We are running kapacitor with 9 tasks (7x stream, 2x batch)
* The tasks are processing metrics for currently ~600 applications
  * 1 stream task receives 1 metric per 10 seconds per application (`task=critical_logs` from the errors above)
  * 3 stream tasks receive 1 metric per 15 seconds per application
  * 2 stream tasks receive 1 metric per 5 minutes per application
  * 1 stream task == `influxDBOut()` (stats about kapacitor)
  * 1 batch task queries 1 measurement for all applications every minute (`task=runtime_heartbeat` from the errors above)
  * 1 batch task queries 1 measurement for 1 application every minute
* The tasks alert to Alerta when a threshold is crossed

The errors above only appear for `task=runtime_heartbeat` and `task=critical_logs`

`runtime_heartbeat` tick script:
```
batch
    |query('''
        SELECT last("value")
        FROM "appmetrics"."autogen"."mendix_runtime.critical_logs_count"
        GROUP BY "app_name"
    ''')
        .groupBy('app_name')
        .period(15m)
        .every(1m)
    @since()
    |alert()
        .info(lambda: "since" <= 600000000000)
        .crit(lambda: "since" > 600000000000)
        .alerta()
            .message('Runtime Heartbeat received {{ index .Fields "since_string" }} ago')
            .resource('{{ index .Tags "app_name" }}')
            .services('mendix_runtime.heartbeat')
            .event('heartbeat')
            .value('{{ index .Fields "since" }}')
```

`@since` is a UDF that basically calculates `time.Now().UnixNano() - p.Time`

`critical_logs` tick script:
```
stream
    |from()
        .measurement('mendix_runtime.critical_logs_count')
        .groupBy('app_name')
    |window()
        .period(1m)
        .every(1m)
    |alert()
        .info(lambda: "value" == 0)
        .crit(lambda: "value" > 0)
        .message('Critical errors count is {{ index .Fields "value" }}.')
        .alerta()
        .resource('{{ index .Tags "app_name" }}')
        .event('critical_logs')
        .value('{{ index .Fields "value" }}')
```

Some graphs to give you an idea how kapacitor is performing:

1h | 12h
------------ | -------------
![kapacitor-memory-1h](https://user-images.githubusercontent.com/548668/34039637-8efa88ba-e190-11e7-81e9-327de1b33639.png) | ![kapacitor-memory-12h](https://user-images.githubusercontent.com/548668/34039677-c0122f84-e190-11e7-958f-49ea44ce5b3c.png)
![kapacitor-cpu-1h](https://user-images.githubusercontent.com/548668/34039645-9aa41d3e-e190-11e7-88d1-c9eea294c60f.png) | ![kapacitor-cpu-12h](https://user-images.githubusercontent.com/548668/34039679-c3c411ec-e190-11e7-8d61-c04546ee24d4.png)
![kapacitor-http-1h](https://user-images.githubusercontent.com/548668/34039651-a3e14d4a-e190-11e7-927c-f7d103b4574c.png) | ![kapacitor-http-12h](https://user-images.githubusercontent.com/548668/34039682-c8ba1570-e190-11e7-8522-639e7053f3f3.png)
![kapacitor-edges-1h](https://user-images.githubusercontent.com/548668/34039654-aaa61656-e190-11e7-8d27-40f3d365f00a.png) | ![kapacitor-edges-12h](https://user-images.githubusercontent.com/548668/34040089-840006ae-e192-11e7-8119-72a4cc9e8438.png)
![kapacitor-errors-1h](https://user-images.githubusercontent.com/548668/34039659-ad98d66e-e190-11e7-89f7-23943cee9f69.png) | ![kapacitor-errors-12h](https://user-images.githubusercontent.com/548668/34039690-d1215278-e190-11e7-82aa-539e9a9197ec.png)

- Is the (magic) number 5000 not high enough for our situation?
- Are we doing stupid things in our tick scripts?
- How can we debug this issue?
- What would be the impact of increasing eventBufferSize to 100,000?
- Is it possible to see how much of the eventBufferSize is used (when there are no errors like these)?

**Comment by pommi** [comment]
Anyone?
