### ISSUE TITLE
Add error counters for every node type

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/kapacitor#1170]
/cc @nathanielc

**Comment by nathanielc** [comment]
Some more details:

Each node in a Kapacitor task keeps track of some counters for events. See https://github.com/influxdata/kapacitor/blob/master/node.go#L104

Every node already has on `avg_exec_time_ns` stat. This issue is to create an `errors` counter for all nodes. And any error log in the node should increment this counter.

**Comment by desa** [comment]
Implemented by https://github.com/influxdata/kapacitor/pull/1175
