### ISSUE TITLE
Have deadman wait for first value and use previous value in alert

### ISSUE THREAD

**Issue by thuey** [influxdata/kapacitor#1189]
I'm following the documentation [here](https://docs.influxdata.com/kapacitor/v1.2/nodes/combine_node/#deadman) in order to implement deadman myself so I can reset the alert. Something _like_ this:
```
 var data = stream
        |from()...
    // Trigger critical alert if the throughput drops below 100 points per 10s and checked 
    // every 10s, and reset the critical alert when throughput increases back over 100 points 
    // per 10s and checked every 10s
    data
        |stats(10s)
            .align()
        |derivative('emitted')
            .unit(10s)
            .nonNegative()
        |alert()
            .id('node \'stream0\' in task \'{{ .TaskName }}\'')
            .message('{{ .ID }} is {{ if eq .Level "OK" }}alive{{ else }}dead{{ end }}: {{ index .Fields "emitted" | printf "%0.3f" }} points/10s.')
            .crit(lambda: "emitted" <= 100.0)
            .critReset(lambda: "emitted" > 100.0)
            .stateChangesOnly()
    //Do normal processing of data
    data...
```

I have two questions. I apologize if this is in the documentation, but I haven't been able to find it:
1. Is there a way to wait until at least one data point has come through before triggering the alert? This would enable me to configure Kapacitor independent of the data it's supposed to be watching. 
2. Is there a way to use fields or tags from the last retrieved value in the message? For example, if I would like my message to include the last value that was retrieved before connection was lost, is there a way to do that?

**Comment by nathanielc** [comment]
The answer to both questions is to use a groupBy statement on the `from` node. This will make the deadman logic operate independently for each group.

Something like this:

```
 var data = stream
        |from()
            .groupBy(*)
  
data
    |stats(10s)
    // The groups carry on from the parent node.
```

In the case of your first question, the first alert will not trigger per group until at least one point arrives for that group. There is one exception, if no data points arrive for any group then an alert will be triggered, since its likely something is not correct at that point.

For your second question you cannot use fields of the point but you can use tags that are part of the groupBy dimensions. In short the groupBy tags from the parent carry down to the alert node but not any of the data.

Also the reset logic doesn't seem to be doing anything different. Meaning the reset condition is the inverse of the trigger condition in your example.

Finally the deaman node can actually be modified this way with expanding it completely. For example the below TICKscrip is equivalent to your example.

```
 var data = stream
        |from()...
    // Trigger critical alert if the throughput drops below 100 points per 10s and checked 
    // every 10s, and reset the critical alert when throughput increases back over 100 points 
    // per 10s and checked every 10s
    data
        |deadman(100.0, 10s)
            .id('node \'stream0\' in task \'{{ .TaskName }}\'')
            .message('{{ .ID }} is {{ if eq .Level "OK" }}alive{{ else }}dead{{ end }}: {{ index .Fields "emitted" | printf "%0.3f" }} points/10s.')
            .critReset(lambda: "emitted" > 100.0)
            .stateChangesOnly()
    //Do normal processing of data
    data...
```

If you were to change the stats or derivative nodes then yes you would need to expand the deadman.

**Comment by thuey** [comment]
Thank you for taking the time to reply and for your promptness.

For your first suggestion, unfortunately, I think I'm running into this exception:
> There is one exception, if no data points arrive for any group then an alert will be triggered, since its likely something is not correct at that point.

I'm working on the sensor system that we have discussed before. We would like our customers to be able to configure alerts before they even have sensors in their hands. So in this case, no groups would have data points until they get their sensors set up. I could work around this limitation by only enabling the TickScript after they configure their sensors, but I was hoping there was some way to communicate this behavior to Kapacitor out of the box.

As per your second suggestion, I have been able to access tags through `{ .Group }`, but only when points are coming through. However, in a true deadman scenario where `emitted` drops to 0, `{ .Group }` is `nil`. Is there a workaround for this? Would it be a good idea to use an HttpOutNode?
> An HTTPOutNode caches the most recent data for each group it has received.

**Comment by thuey** [comment]
Actually, giving it more thought, I realized for the first scenario I can just ignore alert messages that don't contain the tags I need. When alerts are trigger, I have Kapacitor post the message to an internal alert system, so I can filter what gets out to the customer.

**Comment by nathanielc** [comment]
@thuey For the tags issue the .Group should only be nil in the case of the exception where no points have arrived. Once at least one point arrives a nil group should never fire again. And all events should have the tags available via the .Group and .Tags template vars.

The nil group thing is a special case where since we haven't received any data we can't tag it as such but since it is a deadman's switch we still need to fire an alert so we just fire an empty alert. 

Your approach to filter out those empty alerts sounds reasonable.

**Comment by thuey** [comment]
@nathanielc Interesting, that was not my experience. I'll try it out again and let you know.

**Comment by thuey** [comment]
@nathanielc Wow, you are absolutely right. I was reading my logs incorrectly before. Thank you for your help!!

**Comment by nathanielc** [comment]
Glad it is working out!
