### ISSUE TITLE
[feature request] Ability to count the number of events (stateCount)

### ISSUE THREAD

**Issue by danyli78** [influxdata/kapacitor#1225]
Use Case: For graph activity that are volatile, it would be great to add a function to count the number of times a field value exceed certain threshold, that way we can weed out the false alerts.

**Comment by phemmer** [comment]
You already can. https://docs.influxdata.com/kapacitor/v1.2/nodes/influx_q_l_node/#count
 `data|where(lambda: "foo" > 90)|count("foofield")`

**Comment by nathanielc** [comment]
@phemmer  That works for all data that has the same timestamp, if you want to count points over a longer duration then you need a stateCount which is basically the same thing as stateDuration but for counts.

**Comment by phemmer** [comment]
I was thinking more along the lines of batches.
On a stream it could only be something which tracks the consecutive count. Wasn't sure that was what was being requested.
However if that is the request, I think it would make sense to add this into the proposed `stateDuration` node, instead of creating a new node, as they are extremely similar. Though configuration might be a little sticky, so any thoughts on the matter? We can make the node emit both a `state_duration` and a `state_duration_count` by default, but how would one change the name of one of the fields? `stateDuration(foo).as('bar','baz')`, `stateDuration(foo).durationAs('bar')`, something else?

**Comment by phemmer** [comment]
Or, what about `stateDuration(foo).unit('points')`, or `.unit('count')`, or some other word?

**Comment by desa** [comment]
So as I understand it, the node would function nearly identically to `stateDuration`, except for instead of yielding the duration, it will yield the count.

**Comment by phemmer** [comment]
The way I look at is that the "count" as we are calling it, is a duration. As you're not just after a count of matching events, you're after a count of *contiguous* matching events, which is a duration. So yes, the idea is that the output simply changes from a time unit to a number-of-points unit.

**Comment by desa** [comment]
@phemmer I kind of like that idea, My only concern is if I'm a user, looking for this functionality, would I think to use `stateDuration`? I think not. Maybe we could modify the name of `stateDuration`.

**Comment by desa** [comment]
Added in https://github.com/influxdata/kapacitor/pull/1216
