### ISSUE TITLE
leaked stream recording goroutine?

### ISSUE THREAD

**Issue by mac01021** [influxdata/kapacitor#1229]
Should this line say `break` instead of continue?  https://github.com/influxdata/kapacitor/blob/950cfe123e93c99bf2ea0bf021b0acbbbdab8ae4/services/replay/service.go#L1254

Otherwise, won't it run forever?

**Comment by nathanielc** [comment]
@mac01021 Thanks for checking. No it will not run forever, the point of the continue is to drain out all points that were in the edge, otherwise the upstream could block writing into the edge.

We could add a comment to explain that better.

Are you experiencing goroutine leaks or where you just looking at the code?

**Comment by mac01021** [comment]
I'm trying to go through my own variant of the "getting started" page (https://docs.influxdata.com/kapacitor/v1.2/introduction/getting_started/) and my 20-second recording never stops running or collects any data (always saying zero bytes).  

I probably just have something wired up wrong, but it got me looking into the code a little bit.

Probably, if my task never receives any data, `e.NextPoint()` blocks forever and so nothing ever gets compared to `stop`?


Anyway, it sounds like this is a non-issue and should be closed.

**Comment by nathanielc** [comment]
The recording will hang if Kapacitor isn't receiving data. Check `kapacitor stats ingress` to confirm.

Your analysis is correct. We need to add a timeout there to help fix this issue.
