### ISSUE TITLE
does TICK script get executed in sequential order

### ISSUE THREAD

**Issue by huangdeheng** [influxdata/kapacitor#1234]
Hello team,

I have a TICK script whose backbone is as below

```
var data = batch
    |query('''select count(foo) from db.rp.bar''')
        .period(1m)
        .every(1m)
        .groupBy('sometag')

data
    @myUDF1
        .someProperty(1)

data
    @myUDF2
        .otherProperty(1)
```

`myUDF1` would generate an intermediate file which would be consumed by `myUDF2`. I name the intermediate file from `myUDF1` with timestamp of `data`, so in `myUDF2` I need to retrieve the file name also from `data`.  I expected the TICK script would get executed in sequential order synchronously. However, it turned out that `myUDF2` sometimes got invoked before `myUDF1` finished. Is it by design or a bug?

If it's by design, how can I ensure `myUDF1` got finished when invoking `myUDF2` in this case? Thanks for help.

**Comment by nathanielc** [comment]
Since both of the UDFs are siblings in the task DAG, in other words they are both children of the same parent node `data` then they are executed in parallel. 

What is the data that you are sharing between the UDFs? Could you simply have the first UDF output to Kapacitor the relevant data and have the second UDF consume that data? Then Kapacitor handles all the data communication instead of the out-of-band file based approach.
