### ISSUE TITLE
Kapacitor in-memory storage questions

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#179]
Hi,

_Continue from https://github.com/influxdata/kapacitor/issues/73#issuecomment-175249878_

As I understand, Kapacitor has in-memory storage instead of influxdb, according to this I have some question before I use it in production.

### Retention policy
Assuming I have _one_ simple alert that checks some measurement (for example cpu_usage) and checks if is it greater than 80 then we are in critical, does kapacitor store the points for cpu_usage forever in ram? what is the retention policy for each alert?

Is it calculated from the alert - for example, alert with only condition - that points won't be saved, but If I have alert that uses window for 10 minutes the points will be stored for 10 minutes?

### Data loss 
If I want to restart kapacitor and I have points in memory or kapacitor restarted for some reason, how can I make sure there is no data loss?

### Stats
How can I see for monitoring kapacitor (itself) purposes how much points are stored in kapacitor?

And just to make sure - the alerts run on every point? or there is some scheduling - for example, every 10 seconds all of the alert are running?

**Comment by nathanielc** [comment]
I think it would be helpful to not think of Kapacitor as an in-memory InfluxDB database but rather a data pipeline. As such if data is still flowing through the pipeline then its in RAM, once the data reaches the end of a pipeline it is forgotten. There is no index or other mechanism where data resides.

Using your alert example here is a TICKscript to do what you describe.

```javascript
stream
    .from().measurement('cpu')
    .alert()
        .crit(lambda: "value" > 80)
        // do something with the alert
       // for example send it to slack.
       .slack().channel('#alerts')
```
Using the above script define a task and show it.

```sh
kapacitor define -name test -type stream -dbrp telegraf.default -tick path/to/above/script.tick
kapacitor show test
```
You should see an output at the end like:

```
DOT:
digraph test {
stream0 -> stream1;
stream1 -> alert2;
}
```

This means that there are three nodes in the data pipeline. First the streamo node that receives all data in the telegraf.default database/retention-policy. Second the stream1 node that selects data relative to the task (aka from the `cpu` measurement). And finally the alert2 node that performs the alert logic.

As the data arrives at Kapacitor it is processed. Let's look at three different points.

1. A cpu point arrives at the stream0 node with a value of 83. It passes through the stream1 node since it matches and then gets passed on to the alert2 node. Since the value is greater than 80 it triggers an alert and a message is sent to the slack channel. Afterward both the point and the alert are forgotten. Kapacitor took action and now is done with that information.

2. A cpu point arrives at the stream0 node with a value of 67. It again passes through the stream1 node since it matched and then gets passed to the alert2 node. This time the value is not > 80 so it is dropped. That is the end, Kapacitor no longer remembers the point.

3. A disk io_time point arrives at the stream0 node but since the point does not match the stream1 node conditions it is dropped. 

Data remains in RAM as long as it is being processed through the pipeline. Once there are no more actions to take with the data it is forgotten. If you want to store the data Kapacitor is processing see https://docs.influxdata.com/kapacitor/v0.10/tick/influx_d_b_out_node/ 

Windows are no exception, it just takes longer for the data to flow through the pipeline. A window can be thought of as a dam that just stops all incoming points and then releases them all at once.

As for the data loss question: at the moment when Kapacitor is restarted it forgets all data that was in the pipeline. Recently a snapshot restore mechanism has been added so the state of a pipeline can be saved and then restored. It is not fully implemented at this point.

And for the stats here is the relevant configuration.

```
[stats]
  # Emit internal statistics about Kapacitor.
  # To consume these stats create a stream task
  # that selects data from the configured database
  # and retention policy.
  #
  # Example:
  #  stream.from().database('_kapacitor').retentionPolicy('default')...
  #
  enabled = true
  stats-interval = "10s"
  database = "_kapacitor"
  retention-policy= "default"
```

**Comment by yosiat** [comment]
WOW!!
Thanks for the great information :+1: 

It really solves my problem :)
Just two more questions:

1. If there is no "storage", this is all in-flight, what is the meaning of retention policy for points?
2. Can I fetch the stats not from kapacitor?  or should I do something like - 
`stream.from().database('_kapacitor').retentionPolicy('default').influxDBout()...`

**Comment by nathanielc** [comment]
1. For Kapacitor the database and retention policy names just serve to scope the data so you know which data you are working with. Other than that they serve no purpose.

2. Yes, this task will save all Kapacitor internal stats in InfluxDB.

```javascript
stream.from().database('_kapacitor').retentionPolicy('default').influxDBOut()
```
 I have defined the above task as a _stats task like so and find it quite handy.

```
kapacitor define -name _stats -type stream -dbrp _kapacitor.default -tick path/to/above/tickscript
```

Also note if you just what a quick glimpse at the important stats without having to write a query, the `kapacitor show task_name` command prints the number of points that have passed through each edge of the pipeline, if the task is running. For example the above DOT would become when the task is running.

```
DOT:
digraph test {
stream0 -> stream1 [label="472"];
stream1 -> alert2 [label="102"];
}
```

 Meaning stream0 has passed 472 points to stream1 while stream1 has only passed 102 points on to the alert2 node.

**Comment by yosiat** [comment]
@nathanielc 

Hi,
Thanks for the quick response :)

I have some questions:
1. If there is no database what is the default "dbrp" if I am using in-memory store and not using influx?
2. I am calling show and don't have the labels [label="472"] ..?

**Comment by nathanielc** [comment]
@yosiat 

1. There is no default. All methods of sending data to Kapacitor require that you specify the dbrp.

2.  The labels will not show up either if the task is not running.
