### ISSUE TITLE
HTTPOut node produces a .gz file

### ISSUE THREAD

**Issue by lpalm** [influxdata/kapacitor#182]
Visiting the URL for the HTTP node downloads a file name TASKNAME.gz, which is really just a plaintext json file with an invalid extension. 

I'm visiting the URL http://kapacitorhostname:9092/api/v1/TASKNAME

Tick script:
stream
  .from()
    .database('DBNAME')
    .measurement('MEASUREMENTNAME')
  .window()
    .period(5s)
    .every(5s)
  .httpOut('TASKNAME')

This means I can't actually see the results in the browser, as I have to rename the auto-downloaded .gz file to .json or .txt. Probably an easy fix as the downloaded file is correct. We just need to give the correct MIME type/extension

**Comment by lpalm** [comment]
By the way, this .gz behavior occurs when accessing the API link from Chrome in a Yosemite Mac.

**Comment by nathanielc** [comment]
As part of the v0.10.0 release the API paths had a breaking change. The `api/v1` was removed so that its paths match InfluxDB for write compatibility. Try removing the `api/v1` part of the path and see if it still has the issue. It is odd that a gz file is being returned and I'll see if I can fix that. See https://docs.influxdata.com/kapacitor/v0.10/tick/http_out_node/ for docs on the correct path.
