### ISSUE TITLE
Async record 

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#186]
Hi,

I have started using the record in Kapacitor and it looks great, but waiting for the duration only to get the record id isn't nice..
For example, consider that I want to wait for 50 minutes, I would like to do something like this:
```
> kapacitor record stream -name cool_alert -duration 50m
{some record id}
> kapacitor record status {record id}
Recording

.. after 50 minutes ..
> kapacitor record status {record id}
Finished!
```

What do you think?

**Comment by nathanielc** [comment]
What are you going to do with the ID before the recording has finished? I agree that having a long running task can be difficult to manage but the current workflow prevents invalid behavior, of trying to use a partially completed ID. Are you trying to programatically interact with recordings?

**Comment by yosiat** [comment]
I am trying to interact programatically, I want to create recording of 1 hour and setting request timeout limit to 1h isn't acceptable.

What I am suggesting is:

- Create recording returns id
- I will check the status of this id and there will be two stats: recording or finished
  - If this is still recording, I will try again later (5 minutes later for example)
- If this is finished I will go to /api/download_recording/{recording id} for example

**Comment by nathanielc** [comment]
@yosiat The underlying API that the `kapacitor` cli tool uses does what you want. At the moment the HTTP API is undocumented because it is still changing. Depending on your requirements you could use the HTTP API directly for now, although you may have to update your code if the API changes. If you want to see how it works look at this code snippet for how to perform a recording and check on its state later. https://github.com/influxdata/kapacitor/blob/master/cmd/kapacitor/main.go#L268-L325

**Comment by yosiat** [comment]
I checked the api and it doesn't work asynchronously,
I sent the next API call:
```http
POST http://localhost:9092/api/v1/record?type=stream&name=cpu_alert&duration=120m
```

And I waited for 2 minutes and didn't got no response, I expected to get response immediately.

**Comment by nathanielc** [comment]
Looks like you are using an older version. Please upgrade to the newest version 0.10.1 and you should see the behavior you expect.

**Comment by yosiat** [comment]
Thanks :+1:
