### ISSUE TITLE
Window works unexpected

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#221]
Hi,

I am using window in my tick script, and I found some weird behaviour with window.
I am emitting data every 1s, and running the next tick script:

```javascript
stream.from().measurement('cpu')
           .window().every(1s).period(20s)
```
Points - [TestStream_Yosi.txt](https://github.com/influxdata/kapacitor/files/119958/TestStream_Yosi.txt)  _this is the same format as the srpl files in the integration tests_

I have checked this tick script (using httpOut) and injected 20 values (every 1s) and got only 19 results (where the last value was 119) and not 20 (and the last value should be 120) as I expected.

I have debugged the window source code and added some log to check the code before line 54 - https://github.com/influxdata/kapacitor/blob/master/window.go#L54,L61
```go
w.logger.Printf("D! Next emit:%s, Current point: %s (value = %v)", wnd.nextEmit, p.Time, p.Fields["value"])
```

And got the next results -
```
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:01 +0000 UTC, Current point: 1971-01-01 00:00:00 +0000 UTC (value = 101)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:01 +0000 UTC, Current point: 1971-01-01 00:00:01 +0000 UTC (value = 102)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:02 +0000 UTC, Current point: 1971-01-01 00:00:02 +0000 UTC (value = 103)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:03 +0000 UTC, Current point: 1971-01-01 00:00:03 +0000 UTC (value = 104)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:04 +0000 UTC, Current point: 1971-01-01 00:00:04 +0000 UTC (value = 105)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:05 +0000 UTC, Current point: 1971-01-01 00:00:05 +0000 UTC (value = 106)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:06 +0000 UTC, Current point: 1971-01-01 00:00:06 +0000 UTC (value = 107)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:07 +0000 UTC, Current point: 1971-01-01 00:00:07 +0000 UTC (value = 108)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:08 +0000 UTC, Current point: 1971-01-01 00:00:08 +0000 UTC (value = 109)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:09 +0000 UTC, Current point: 1971-01-01 00:00:09 +0000 UTC (value = 110)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:10 +0000 UTC, Current point: 1971-01-01 00:00:10 +0000 UTC (value = 111)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:11 +0000 UTC, Current point: 1971-01-01 00:00:11 +0000 UTC (value = 112)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:12 +0000 UTC, Current point: 1971-01-01 00:00:12 +0000 UTC (value = 113)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:13 +0000 UTC, Current point: 1971-01-01 00:00:13 +0000 UTC (value = 114)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:14 +0000 UTC, Current point: 1971-01-01 00:00:14 +0000 UTC (value = 115)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:15 +0000 UTC, Current point: 1971-01-01 00:00:15 +0000 UTC (value = 116)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:16 +0000 UTC, Current point: 1971-01-01 00:00:16 +0000 UTC (value = 117)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:17 +0000 UTC, Current point: 1971-01-01 00:00:17 +0000 UTC (value = 118)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:18 +0000 UTC, Current point: 1971-01-01 00:00:18 +0000 UTC (value = 119)
[TestStream_Yosi:window2] 2016/02/06 00:38:30 D! Next emit:1971-01-01 00:00:19 +0000 UTC, Current point: 1971-01-01 00:00:19 +0000 UTC (value = 120)
```

As you can see the the last line, we should emit the value 120, and I have digger more.. and put log to see the first value and the last value of every emit and saw that -
```
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 1 points, first 101 and last 101
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 2 points, first 101 and last 102
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 3 points, first 101 and last 103
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 4 points, first 101 and last 104
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 5 points, first 101 and last 105
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 6 points, first 101 and last 106
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 7 points, first 101 and last 107
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 8 points, first 101 and last 108
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 9 points, first 101 and last 109
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 10 points, first 101 and last 110
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 11 points, first 101 and last 111
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 12 points, first 101 and last 112
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 13 points, first 101 and last 113
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 14 points, first 101 and last 114
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 15 points, first 101 and last 115
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 16 points, first 101 and last 116
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 17 points, first 101 and last 117
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 18 points, first 101 and last 118
[TestStream_Yosi:window2] 2016/02/06 00:42:29 D! Emitting 19 points, first 101 and last 119
```
The last value is skipped.

I have did little code change, to insert to the window buffer before emitting and it fixed the problem,
the logs now looks like this:

Window emits:
```
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 2 points, first 101 and last 102
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 3 points, first 101 and last 103
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 4 points, first 101 and last 104
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 5 points, first 101 and last 105
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 6 points, first 101 and last 106
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 7 points, first 101 and last 107
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 8 points, first 101 and last 108
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 9 points, first 101 and last 109
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 10 points, first 101 and last 110
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 11 points, first 101 and last 111
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 12 points, first 101 and last 112
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 13 points, first 101 and last 113
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 14 points, first 101 and last 114
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 15 points, first 101 and last 115
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 16 points, first 101 and last 116
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 17 points, first 101 and last 117
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 18 points, first 101 and last 118
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 19 points, first 101 and last 119
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Emitting 20 points, first 101 and last 120
```

Next emit debug:
```
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:01 +0000 UTC, Current point: 1971-01-01 00:00:00 +0000 UTC (value = 101)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:01 +0000 UTC, Current point: 1971-01-01 00:00:01 +0000 UTC (value = 102)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:02 +0000 UTC, Current point: 1971-01-01 00:00:02 +0000 UTC (value = 103)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:03 +0000 UTC, Current point: 1971-01-01 00:00:03 +0000 UTC (value = 104)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:04 +0000 UTC, Current point: 1971-01-01 00:00:04 +0000 UTC (value = 105)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:05 +0000 UTC, Current point: 1971-01-01 00:00:05 +0000 UTC (value = 106)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:06 +0000 UTC, Current point: 1971-01-01 00:00:06 +0000 UTC (value = 107)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:07 +0000 UTC, Current point: 1971-01-01 00:00:07 +0000 UTC (value = 108)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:08 +0000 UTC, Current point: 1971-01-01 00:00:08 +0000 UTC (value = 109)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:09 +0000 UTC, Current point: 1971-01-01 00:00:09 +0000 UTC (value = 110)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:10 +0000 UTC, Current point: 1971-01-01 00:00:10 +0000 UTC (value = 111)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:11 +0000 UTC, Current point: 1971-01-01 00:00:11 +0000 UTC (value = 112)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:12 +0000 UTC, Current point: 1971-01-01 00:00:12 +0000 UTC (value = 113)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:13 +0000 UTC, Current point: 1971-01-01 00:00:13 +0000 UTC (value = 114)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:14 +0000 UTC, Current point: 1971-01-01 00:00:14 +0000 UTC (value = 115)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:15 +0000 UTC, Current point: 1971-01-01 00:00:15 +0000 UTC (value = 116)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:16 +0000 UTC, Current point: 1971-01-01 00:00:16 +0000 UTC (value = 117)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:17 +0000 UTC, Current point: 1971-01-01 00:00:17 +0000 UTC (value = 118)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:18 +0000 UTC, Current point: 1971-01-01 00:00:18 +0000 UTC (value = 119)
[TestStream_Yosi:window2] 2016/02/06 00:41:44 D! Next emit:1971-01-01 00:00:19 +0000 UTC, Current point: 1971-01-01 00:00:19 +0000 UTC (value = 120)
```

Is this a bug? I can write integration test for showing the bug if this is needed.

**Comment by nathanielc** [comment]
That last value is not skipped its just still sitting in the window waiting to be pushed out by then  next point behind it.

Add one more point:
```
dbname
rpname
cpu,type=idle,host=serverA value=121 0000000021
```
to your test file and see that value 120 will come out. 

This is an artifact of how Kapacitor is designed to use the time of data points to understand time instead of real time. This means that unless a new data point comes along time never progresses and the window waits forever to emit the point. You will notice that there are always a few extra data points in the integration test files for exactly this purpose. 
For infinite streams this is not a problem as there will always be another point to push along the existing points. 

The common use cases of Kapacitor are infinite streams, meaning there is no known end to the stream. Do you have a use case that specifically requires an exact amount of data to be processed? If so it might be possible to add some kind of flush mechanism to the pipeline so that all points are processed even if no new points arrive.

**Comment by yosiat** [comment]
WOW that was fast time to answer :+1:  :+1: 

I am trying to use Kapacitor as engine for real time alerting, that behaviour you are describing seems like an latency issue If I am using window.

Instead of sending the alert as soon as possible (In our case, when value "120" arrives) I will get in the next arrival of event, It means in my system I will always have a latency of time difference between the "120" event and the "121" event.

I see that you are describing this as an design artifact, but as I showed there is an easy fix for this problem, why not considering it?

**Comment by nathanielc** [comment]
By inserting the data point before the emit you no longer have a deterministic windowing mechanism. What if multiple  points arrive for the same time? By inserting after the emit you guarantee that all points for time have arrived before emitting. If you insert before you emit then you emit when the first point arrives for the time not the last. 

Kapacitor works under the assumption that data arrives increasing time values. It cannot know that no more data for a given time is going to arrive until a point with a greater time arrives. In short the window is defined as [start,stop) meaning that if a point arrives on a boundary it belongs to the start of the window not the end.

If you run the tests with your change you will see that most of the integration tests fail. 

Yes there is a latency issue equal to the *every* value of the window. I am open to suggestions for how to remove it.  On a slightly different note I am working on putting together tools to measure both the throughput and latency of Kapacitor. That way you can make informed decisions when designing systems around Kapacitor.

**Comment by yosiat** [comment]
Oh.. I understand..

You talked about implementing flush mechanism, I thought about some mechanism:

Given this tick script:
```javascript
window().every(1s).period(20s).flush(1s)
```

The code will stay the same, but the window node will create a timer that will dispatch event every flush (in our case every one second) that will call "wnd.emit".

What do you think?

**Comment by nathanielc** [comment]
I like the idea it was proposed before for a slightly different use case. See #137.

While a flush mechanism like that can remove the long tail latency(meaning the last point hanging out indefinitely) it does not remove the latency of the every value. Each point will still have to wait in the window for 1s.

Also adding the flush mechanism to the window it self could cause really weird issues. Namely odd race conditions if you have more than one window etc. This is the reason why time is measured by the data in the first place.

My thought for the flush mechanism was to optionally configure one for the entire task. Then use the fact the Kapacitor understands the pipeline topology to flush nodes from top to bottom so that consistency can still be guaranteed. Not sure if this is possible but seems useful. But as soon as you do something like this it adds lots of complexity because you can easily violate the underlying assumptions of how Kapacitor data flow system works. And  this still only removes the long tail latency not the inherent latency in the window node itself. 


Before we go much further down this path what is your *real time* use case and how would this latency effect it?

* Which latency issue is the most concerning?
   1. The fact that the last point can hang around until a new point arrives.
   2. The fact that each point is delayed in the window for the `every` duration.
* Do you expect your data stream to stop for long periods of time?
* What is the effect of a latent response from Kapacitor?
* Do you need the window? Aka what aggregation/transformation are you performing?

Just some questions to answer before we go and implement a difficult feature if we don't really need it.

**Comment by yosiat** [comment]
- The most concerning latency issue I have is: "The fact that the last point can hang around until a new point arrives.".
- The only reason a data stream can stop of a long periods of time is when a server goes down (I am using Kapacitor as monitoring applications)
- The effect of latent response from Kapacitor will be latent alert, in a real time system a matter of seconds is crucial (In the real world, point comes every 10 seconds and not every 1 second)

he reason (that) we need new guidelines is that the present ones are just not working.

The reason I need window is that currently I am replacing legacy alert system with rate operation,  which works that way:
For example the rate interval is 20 seconds and the sample interval is 1 second and we have the same data from TestStream_Yosi (whom attached at the original issue).
When 121 will arrive, I will calculate the difference between this point and 20 seconds worth point behind, thus, 121 - 101 => rate will be 20.

The tick script for this, is:
```javascript
var rateInterval = 20s
var sampleInterval = 1s

// Create window stream of the data
var windows = stream
	.from()
		.database('dbname')
		.retentionPolicy('rpname')
		.measurement('cpu')
		.where(lambda: "host" == 'serverA')
	.window()
		.period(rateInterval)
		.every(sampleInterval)

// Ge the current and the previous of each window,
// which is the first and the last value of each window.
var previous = stream.mapReduce(influxql.first('value'))
var current = stream.mapReduce(influxql.last('value'))


// Calculate the rate as current - previous
previous.join(current).as('previous', 'current')
		.eval(lambda: "current.first" - "previous.first").as('rate')
```

I am not sure, I am pretty confused about this, but It might be the implementation of difference in influxdb but with controlling of the time window.

Just to make sure, the latency we are talking here, is only in "window" function? or other functions have them?

**Comment by yosiat** [comment]
@nathanielc any ideas? response?

**Comment by nathanielc** [comment]
@yosiat Yes I have been thinking about your use case. I think Kapacitor is well suited for your needs as is. Let me explain:

* There is a way to trigger an alert if the data stream stops. See deadman's switch. https://docs.influxdata.com/kapacitor/v0.10/tick/stream_node/#deadman  With that you shouldn't have to worry about missing a dead server.
* What process is responding to the alert? What is the mean time to response of that processes? Meaning on average how long does it take to respond to an alert? Is it greater than 1s? If it is a human it most definitely is. In the case that the MTTR > 1s  the 1s lag is not a practical concern. If the alert is sent to another system that responds much faster then we do have a problem, but I haven't seen you mentioned anything like that.
* Yes the window function is what creates the latency. Derivative has a similar issue since it waits for two points before it can emit the difference, but that is only on the first point. 

Your TICKscript looks good, but with one small typo, it should read:

```javascript
// Calculate the rate as current - previous
previous.join(current).as('previous', 'current')
        .eval(lambda: "current.last" - "previous.first").as('rate')
```

Have you tried this script out? Does it work? What issues have you run into in practice?

**Comment by yosiat** [comment]
Hi,
I have tried this script out (without the typo ;) ) and found some weirdness in window behaviour.

The first test which **passed** is:
Insert to Kapacitor (using http api) 20 points, where the time delta is 10 second between each point and the values increments linearly - +5 every point (0,5,10).
As I expected when I configured the period for the window to be 50 seconds - I got 5 points in each window batch.

After this is test passed, I changed it to be more like the real world, where I don't send data exactly every 10 seconds, but every 10 + rand(0,5) seconds (to simulate real world "latency"), then the window started to do some odd things.
At the started the window size grows nicely from 1 to 5 and as the points count grows so the window size - I got **8 points in a window**.

I thought this was bug In my tick script/code, so I wrote UDF to dump all point batches to file (where each line - is json dump of the batch, and each batch contains point that looks like this: { "time".., "value".. } ).
I took the batch with 8 points, and calculate the time delta between the last point and the first point and it was more than 50 seconds, it was 80 seconds.

I don't understand how this happened.

_I will update this comment with some sample data to reproduce the problem_

**Comment by nathanielc** [comment]
> I will update this comment with some sample data to reproduce the problem
Great, thanks for the detailed report.

**Comment by yosiat** [comment]
Ok, I have have create gist with all data - 
https://gist.github.com/yosiat/25712097b9e5b0e920c9

TICK script:
```
stream
 		.from().measurement('window_data')
    .window().every(10s).period(50s)
    .mapReduce(influxql.count('value'))
    .alert()
        .crit(lambda: TRUE)
				.log('/Volumes/Data/influx/alerts.log')
```

Explanation of the files:

- OK test: ok.log, ok.stdout, ok_insert.rb
- Fail test: random.log, random.stdout, random_insert.rb

_Between each run I have disabled & enabled the task_

As you can see the values in the "random.log" is 1 and grows to 8.

**Comment by yosiat** [comment]
@nathanielc What is going on? Currently I am stuck.

BTW - Why you are using doubling the size of the ring buffer and not using max value of the ring buffer which can be calculate via = period/every + 1(for modulo) ?

**Comment by nathanielc** [comment]
@yosiat This is fixed and will be part of the nightly build tonight (midnight PST)

**Comment by yosiat** [comment]
@nathanielc Thanks for the quick fix, but there is still a bug :(

Let's look at this data (with random added):
```
Inserting 1455819359 = 5
Inserting 1455819371 = 10
Inserting 1455819386 = 15
Inserting 1455819400 = 20
Inserting 1455819414 = 25
Inserting 1455819426 = 30
Inserting 1455819440 = 35
Inserting 1455819450 = 40
Inserting 1455819464 = 45
Inserting 1455819478 = 50
Inserting 1455819491 = 55
Inserting 1455819502 = 60
Inserting 1455819516 = 65
Inserting 1455819527 = 70
Inserting 1455819538 = 75
Inserting 1455819553 = 80
Inserting 1455819566 = 85
Inserting 1455819579 = 90
Inserting 1455819592 = 95
Inserting 1455819602 = 100
```

I am getting a groups of 4 instead of groups of 5, and I will explain.
Here is the alerts file in a gist (with script to format the results, and formatted results) -
https://gist.github.com/yosiat/7d54089c6563f9075113

The alert is created using this tick script:
```
var windows = stream
    // Select just the cpu_usage_idle measurement from our example database.
		.from().measurement('window_data')
    .window().every(10s).period(50s)


var first = windows.mapReduce(influxql.first('value'))
var last = windows.mapReduce(influxql.last('value'))
var count = windows.mapReduce(influxql.count('value'))


first.alert().crit(lambda: TRUE).log('/Volumes/Data/influx/alerts.log')
last.alert().crit(lambda: TRUE).log('/Volumes/Data/influx/alerts.log')
count.alert().crit(lambda: TRUE).log('/Volumes/Data/influx/alerts.log')
```

To understand my point, why we should get groups of 5, lets look at this result:
```
Time: 2016-02-18T18:19:49Z
First: 80, Last: 90, Count: 3
```

The first is 80 and the last 90, the delta between them is:
1455819579 - 1455819553 = 26

But why I didn't get a group with 90 and 75 where their delta is:
1455819579 - 1455819538 = 41

Where 41 enters in my period.

**Comment by nathanielc** [comment]
> But why I didn't get a group with 90 and 75 where their delta is:
1455819579 - 1455819538 = 41
Where 41 enters in my period.

The reason is that the window is not computing continuous periods but rather discrete periods. Meaning that just because two points are less than period apart it is not gauranteed that they exist in a window together. Treating the window and the data like waves the `phase` and `period` have to match inorder for the group to get created. 

For your example time starts at 1455819359, since the times are relative we can subtract `1455819000` seconds so that time T0 is 359, so its simpler to read.

Since T0 is at 359 each window will have a start and end values at 10s intervals from time T0 (359). 

Windows are defined by an inclusive start time and an exclusive end time. For example the zeroth window is [T0-50, T0). Where `[` means inclusive and `)` means exclusive. More explicitly the zeroth window includes points in the time range [309 - 359), Since the first point is at time 359 it is not included in the zeroth window but rather the first window [T0+10-50, T0 +10) or [319, 369). Continuing that pattern you can see that the 21st through 24rd windows contain the points 90 or 75. Since point 90 is at time 579 it lands right on one of the window boundaries.

```
T21 = [519, 569) : [85, 80, 75, 70]
T22 = [529, 579) : [85, 80, 75] // Note 90 is at 579 but the bounds are right hand exclusive
T23 = [539, 589) : [90, 85, 80]
T24 = [549, 599) : [95, 90, 85, 80]
```

We can see that there is no window that includes both 90 and 75. This is because not all windows of length 50s are found but rather only the windows that are on the 10s boundary from the first point. In general the problem you  are seeing is highly related to aliasing https://en.wikipedia.org/wiki/Aliasing from signal processing and should be considered when windowing data. 

There are two things you can do to mitigate these odd window boundaries:

1. Use a smaller `every` value as that in effect increases your sampling rate, akin to https://en.wikipedia.org/wiki/Nyquist_frequency again from signal processing.
2. The window node has an `align` property that instructs it to align the boundaries on consistent times instead of when the first data point arrives. https://docs.influxdata.com/kapacitor/v0.10/tick/window_node/#align

In general these small issues should not cause significant problems unless you really are doing  [signal processing](https://en.wikipedia.org/wiki/Signal_processing) work. In which case you should just apply the appropriate filters etc to your data set before windowing. 

Here is a list of all windows from the example data.

```
T00 = [309, 359) : [] // the T0 window is always empty so it is not output
T01 = [319, 369) : [5]
T02 = [329, 379) : [10, 5]
T03 = [339, 389) : [15, 10, 5]
T04 = [349, 399) : [15, 10 , 5]
T05 = [359, 409) : [20, 15, 10, 5]
T06 = [369, 419) : [25, 20, 15, 10]
T07 = [379, 429) : [30, 25, 20, 15]
T08 = [389, 439) : [30, 25, 20]
T09 = [399, 449) : [35, 30, 25, 20]
T10 = [409, 459) : [40, 35, 20, 25]
T11 = [419, 469) : [45, 40, 35, 30]
T12 = [429, 479) : [50, 45, 40, 35]
T13 = [439, 489) : [50, 45, 40, 35]
T14 = [449, 499) : [55, 50, 45, 40]
T15 = [459, 509) : [60, 55, 50, 45]
T16 = [469, 519) : [65, 60, 55, 50]
T17 = [479, 529) : [70, 65, 60, 55]
T18 = [489, 539) : [75, 70, 65, 60, 55]
T19 = [499, 549) : [75, 70, 65, 60]
T20 = [509, 559) : [80, 75, 70, 65]
T21 = [519, 569) : [85, 80, 75, 70]
T22 = [529, 579) : [85, 80, 75] // Note 90 is at 579 but the bounds are right hand exlcusive
T23 = [539, 589) : [90, 85, 80]
T24 = [549, 599) : [95, 90, 85, 80]
T25 = [559, 609) : [100, 95, 90, 85] // This window is not returned since time does advance enough for it to be emitted.
```

**Comment by yosiat** [comment]
Thanks for the response :+1: I have checked this with "align()" enabled and it worked ok, I got groups of 50 seconds.

Thanks again :+1:

**Comment by Kaacz** [comment]
**BIG** thank to @nathanielc for great explanation.
