### ISSUE TITLE
REST api documentation

### ISSUE THREAD

**Issue by arussellsaw** [influxdata/kapacitor#253]
i'd like to make a web client for kapacitord in order to make managing alerts a little easier, but i can't find any docs for the REST api. even an autogenerated list of all handlers and their roles would be helpful.

**Comment by nathanielc** [comment]
@arussellsaw ATM the REST API is not documented since it is subject to change. Once its been stable for a release or so we will lock it down and document it. For now your best reference is here https://github.com/influxdata/kapacitor/blob/master/cmd/kapacitor/main.go 

Sorry for not having anything better but docs are coming...

**Comment by earthnut** [comment]
@nathanielc  is there any authentication built in ?

I see 
> auth-enabled = false
in the config. I tried to change false to true, but it seems nothing changed.

**Comment by nathanielc** [comment]
@earthnut Not yet, but soon :)

**Comment by nathanielc** [comment]
Closing. See https://github.com/influxdata/docs.influxdata.com/pull/426
