### ISSUE TITLE
Wildcard measurement name matches

### ISSUE THREAD

**Issue by yosiat** [influxdata/kapacitor#271]
Hi,

Does kapacitor supports wildcard measurement names?
For example: `*.name` will match `yosi.name` and yosi.attias.name

And:  `*.*.name` will match `yosi.attias.name`

**Comment by nathanielc** [comment]
It does not. The expectation is to use tags. Is there a reason you are creating specially named measurements? We could potentially add a regex option without too much effort but that would be slow compared to a simple string compare. Also if you don't specify a measurement all measurements will be used.

**Comment by yosiat** [comment]
I beed this because I am flatenning my metrics tree to leafs and I want in some alerts to check against all leaf that are named "name" (see original example)

**Comment by nathanielc** [comment]
Why not use a tag for the leaf name part then. For example,

Measurement name: yosi.attias
tags name: 'actualname'

Then in TICKscript

```javascript
stream.from().measurement('yosi.attias').where(lambda: "name" == 'actualname')
```
or even group by name:
```javascript
stream.from().measurement('yosi.attias').groupBy('name')
```

If you don't use a tag you will not be able to group the data. The data from all matching measurements would be mixed together and you would not be able to separate it out.

**Comment by yosiat** [comment]
I can't use tags because I want partial parts of the tree, for example: `Root.*.value` 
Can't it be some special flag to enable this? 

By the way - this feature is supported in influxdb..

**Comment by yosiat** [comment]
@nathanielc what do you say? are open to pull request to this?

**Comment by nathanielc** [comment]
@yosiat Would you expect a set of measurements that are selected via a wildcard to be automatically grouped by measurement or do you want to process the union of all the data?

Tags are intended to be used precisely for selecting partial trees. Tags provide an orthogonal basis on which to project your data. Using tags you can easily select any subset of the data desired. 

As for the PR, depending on the answer to the first question its either trivial or a significant amount of work to support wildcard matching.

**Comment by yosiat** [comment]
Umm let's me explain, For example I write `a.*.c` and checks that the value is greater than 20 if so create alert. So I expect there to be **two alerts, alert per match** - one alert for "a.b.c" and one alert for "a.z.c" without any relation.

It will be much harder to implement.. is this possible in Kapacitor?

**Comment by nathanielc** [comment]
Not in the current implementation. If you use tags then it is possible.

We should probably make Kapacitor behave the way you describe, but it currently does not. Instead, the alert state will be maintained for the union of all `a.*.c`  measurements.

**Comment by yosiat** [comment]
This feature is crucial for my use in Kapacitor (80% of my alerts depends on it).
How the next matches are possible with tags?
`a.*.c` should match `a.b.c` `a.z.c`
`*.c` should match `a.b.c` `a.c`

And how hard will it be to implement this in Kapacitor? I will be more than happy to submit pull request.

**Comment by nathanielc** [comment]
What do the `b` and `z` names represent? Since I don't know I'll just call it `middle`.

Change a name like `a.b.c` to `a.c` with a tag `middle=b`,
 likewise `a.z.c` to `a.c` with a tag `middle=z`

Then in TICKscript its just:

```
stream.from().measurement('a.c').groupBy('middle')
```

You can repeat the above process as many times as necessary till your measurement names no longer encode any extra information. See this https://docs.influxdata.com/influxdb/v0.10/concepts/schema_and_data_layout/ for more bests practices on schema design.

**Comment by nathanielc** [comment]
As for the `*.c` should match `a.b.c` `a.c` what does it mean to have a name `a.c` without a middle part? Is it empty? If so give it an empty tag.

**Comment by yosiat** [comment]
Let me explain the whole flow of ingesting metrics in my system and you will that will tags it isn't possible.
In my system, each server build a tree of metrics, for example:
```
App1
   Info
      Cpu = 80%
      Memory = 3gb
    AppController1
      RequestsPerSecond = 200
   AppController2
      RequestsPerSecond = 120
```

Those tree are flattened and inserted to kapacitor (App.Info.Cpu, App.AppController2.RequestsPerSecond) and etc.

In a later phase the user (developer) can create alert based on this tree and can say - "I want to check that all of my ReuqestsPerSecond are greater than X" - so there will be alert on "App1.*.AppController2".

And it is important to say that the **structure of those tree vary between each app**, It will be hard to these with tags.

I don't see another option other than implementing this in Kapacitor, I can devote my full time to developing this in Kapacitor - I just need few pointers and you estimate of difficulty in implementing this in Kapacitor (major change? going deeper to the internals?)

**Comment by nathanielc** [comment]
@yosiat Unfortunately it will require digging into the internals to get it to work. It is probably something that should be done and I'll add some pointers below on what needs to be done, but first (I may be annoying/frustrating at this point) but I still think you can use tags ;)

To be clear I am not pushing back because I don't want to implement the feature but rather I think you will have a better experience if you do switch to using tags. Let me try and explain in detail how that could work.

Lets take two apps each with very different metric trees.

```
App1
   Info
      Cpu = 80%
      Memory = 3gb
   AppController1
      RequestsPerSecond = 200
      ErrorsPerSecond = 5
   AppController2
      RequestsPerSecond = 120
      ErrorsPerSecond = 2

App2
   Info
      Cpu = 85%
      Memory = 4gb
    AppController1
      RequestsPerSecond = 200
      AverageRequestLatency  = 250ms
    AppController2
      RequestsPerSecond = 120
      AverageRequestLatency  = 150ms

```

Ok so now we have two different apps called `App1` and `App2` and they are reporting different metrics. If I understand correctly currently you are using named measurements like `App1.cpu` and `App2.AppController1.RequestsPerSecond` to store each metric. And you want to be able to do things like `App2.*.RequestsPerSecond` 
 to get the RequestsPerSecond for each controller for `App2`.

So if we flip this tree on it head we have a bunch types of data we call `measurements` aka `RequestsPerSecond`, `AverageRequestLatency`, `Memory`, `CPU` etc. Then each piece higher up the tree gets a label and a value.

For example  `App1.cpu` becomes `cpu,app=App1`(using influxdb line protocol syntax) meaning the data goes into a measurement `cpu` and has a tag `app=App1`.  Similarly `App2.cpu` becomes `cpu,app=App2`. Then to work with the cpu data in TICKscript its:

```javascript
stream
    .from()
        .measurement('cpu')
        .groupBy('app')
```

Now lets look at `RequestsPerSecond` which has more levels in the tree than the cpu metric.

* `App1.AppController1.RequestsPerSecond` -> `RequestsPerSecond,app=App1,controller=AppController1`
* `App1.AppController2.RequestsPerSecond` -> `RequestsPerSecond,app=App1,controller=AppController2`
* `App2.AppController1.RequestsPerSecond` -> `RequestsPerSecond,app=App2,controller=AppController1`
* `App2.AppController2.RequestsPerSecond` -> `RequestsPerSecond,app=App2,controller=AppController2`

Then to get all controllers for App2 its, 

```javascript
stream
    .from()
        .measurement('RequestsPerSecond')
        .where(lambda: "app" == 'App2')
        .groupBy('controller')
```
or if you and alert for all controller per app

```javascript
stream
    .from()
        .measurement('RequestsPerSecond')
        .groupBy('app', 'controller')
```


Finally you can write a task like this to check error rates.

```javascript
stream
    .from()
        .measurement('ErrorsPerSecond')
        .groupBy('app', 'controller')
```

And since App2 doesn't report `ErrorsPerSecond` second it won't be included in the data set and only App1 will be monitored. Then if App2 were to start reporting `ErrorsPerSecond` it would automatically get picked up by the same task.


By using a combination of `where` expressions and `groupBy` you can select any sub set of the data you want.

**Comment by yosiat** [comment]
Hi @nathanielc ,
You are not frustrating :) you are just trying to understand my problem and it's more than OK :) :+1: 

The problem is that (and maybe I am clear about this) that the structure of the tree can vary from app to app, one app can produce:
```
App1
   Info
      Cpu = 80%
      Memory = 3gb
   AppController1
      RequestsPerSecond = 200
      ErrorsPerSecond = 5
   AppController2
      RequestsPerSecond = 120
      ErrorsPerSecond = 2
```

While the other will produce:
```
MyThing
   Info
      Cpu = 80%
      Memory = 3gb
   ConnectedUsers
      Count = 10
      List: [ "yosi", "nathaniel" ]
   ClickMetrics
      ClicksPerSecond = 120
``

And my system gets all of those dynamic tree and don't know there semantic meaning (that "AppController1" is controller) therefore I can't tag it.

I have started to learn the internals of Kapacitor (for the "high cpu usage" and for window bug) so let's try it :)

**Comment by yosiat** [comment]
@nathanielc it looks my patch solution didn't work.
My best solution for now is to create udf that will connect to "stream" and will filter using wildcards

**Comment by yosiat** [comment]
@nathanielc After thinking about this, why this is so hard for supporting regex in measurement name? Is this because the performance penalty?

**Comment by nathanielc** [comment]
@yosiat Setting up the wildcard matching is not difficult. The problem is that each selected measurement will get union-ed together and will not be processed independently. Since it is the responsibility of each node to handle how groups are processed this change means updating the logic for all nodes to use the measurement name as part of the group ID. There are helper methods for this but it is a breaking change and there are lots of edge cases to handle. For example what measurement name does a joined set of measurements get? etc.

I didn't see your edit till now, but it sounds like you are headed in the right direction. The only potential pitfall I see is that by suing the full measurement name and regex you will not be able to group by anything but the full name. 

Using multiple tags is efficient and the expected usage of Kapacitor. What specifically didn't work with the first attempt at using tags?

**Comment by yosiat** [comment]
@nathanielc the first attempt using tags didn't worked because I assumed wrong assumptions (and not becasue Kapacitor didn't allow me to).

When I am using regex in the path I want separate alert (and we can think about it as separate task) for each group, for example:
a.*.c -> a.b.c and a.z.c will be two different alerts, so I don't need to group by (If will groupBy it will be the application type or something like this)

**Comment by sslupsky** [comment]
Hi @nathanielc 

I have just run into a similar problem.  I have several measurements.  Let's call them P1.a, P1.b, P1.c, P2.d, P2.e, P3.f.  Each measurement has several fields.  Let's call the fields "C1, C2, C3".  I would like to create one node in Kapacitor to check one of the fields in all of the measurements against and threshold and generate an alert.  Thus,

SELECT mean("C1") FROM "metrics"."default"./P1*/

The problem as you described is that the measurements get union-ed together.  I desire that each measurement is unique.  In effect, a "groupBy measurement" is what is required.

I cannot use tags because the cardinality is high.  Which is precisely why I want to code a single node in tick script so that I do not have to constantly update the tick script when I add a new measurement.

**Comment by forestjohnsonpeoplenet** [comment]
I wrote a UDF to solve this issue: https://gist.github.com/forestjohnsonpeoplenet/f0aa7a807f0f1735ea02279338cdeaf1

You would use it like so:

```
stream
   |from()
     .database('myDatabase')
   @createTagFromMeasurementName()
   |where(lambda: "measurementName" !~ /someKoolREgexBro/)
   |delete()
     .tag('measurementName')
   |influxDBOut()
```
