### ISSUE TITLE
TICK script - how to find elapsed time between two measurement points

### ISSUE THREAD

**Issue by vlasov01** [influxdata/kapacitor#384]
I'm having difficulties to create a TICK script, that can find elapsed time between two measurement points. My Influx Measurement contains state points with values "on" and "off" (always in this order). I'd like to trigger event once "off" state arrives and calculates elapsed time between "on" and "off" state.

**Comment by nathanielc** [comment]
@vlasov01 There is no clean way to do this within Kapacitor at the moment.

One way I can think to do this is to use the `derivative` method, its really hacky but if `on` had a value of `0` and `off` had a value of `1` then then the derivative was computed it would do:
` (1 - 0 / elapsed)` and then you could use an eval node to invert the result and get elapsed back out. 

Since the above method is really confusing and fragile we should probably add a method for computing elapsed times. Maybe something as simple as:

```
stream
     .from()....
     .elapsed()
          .as('elapsed')
     .alert()
         .crit(lambda: "status" == 'off')
         .message('Elapsed time: {{ index .Fields "elapsed" }}')

```

Would that fit your needs?

Can you provide more context about what you are trying to do with the elapsed time as this seems like an interesting use case?

**Comment by vlasov01** [comment]
@nathanielc Thank you for the prompt reply!
I'm using Kapacitor v0.11. I've implemented script based on your code sample.
```
var online = stream
    .from().measurement('watersensor')
    //.where(lambda: "last" == 'offline')
    .elapsed()
         .as('elapsed')
    .alert()
         .info(lambda: "state" == 'offline')
         .message('Elapsed time: {{ index .Fields "elapsed" }}')
         .log('/var/log/kapacitor/summary.log')
```
But getting the following error when trying to define script:
invalid task: No method or property "elapsed" on

A bit about my use case:
The water sensor controller is switches into an "online" state when water is switched on and switches to an "offline" state once water flow stops. I'd like to measure the elapsed time of water flow. These points are accumulated in the "watersensor" measurement.
At the same time, controller is publishing every 5 seconds amount of water used. These points are accumulated in the "water" measurement.
Once water flow stops ("watersensor" state=="offline") I'd like to calculate summary of water used and how much time it was on and publish info/warn/crit alert,

**Comment by vlasov01** [comment]
@nathanielc It seems the proposal #388 looks a bit similar.
But now I'm thinking may be it makes more sense to implement it directly as a continuous query as per https://docs.influxdata.com/influxdb/v0.11/query_language/continuous_queries/ ?
