### ISSUE TITLE
Arithmetics is wrong in eval method

### ISSUE THREAD

**Issue by madshall** [influxdata/kapacitor#429]
The TICK script contains: 
```
stream.eval(lambda: "val1" / "val2" * 100.0)
	.as('newVal')
```
When it comes down to log file I see the `newVal` being 10000 less than expected.

This works fine though:
```
stream.eval(lambda: 100.0 * "val1" / "val2" )
	.as('newVal')
```

Using v0.11.0

**Comment by nathanielc** [comment]
@madshall Sorry for taking so long to get back to you.

Looking back at the TICKscript parser it was implemented as a right-associative parser which is confusing since most expressions parsers use left-association. TICKscript is interpreting the expression as 

`stream.eval(lambda: "val1" / ("val2" * 100.0))` which isn't what you meant.

We should change the association of the parser. We will use this issue to track the change.
