### ISSUE TITLE
Batch query multiple measurements but alert only on 1 measurements

### ISSUE THREAD

**Issue by earthnut** [influxdata/kapacitor#466]
I have one task :
> batch
    |query('''
         SELECT sum("value") as livecount
         FROM "collectd"."default"./process_.*/ fill(0)
     ''')
        .period(1m)
        .every(30s)
        .groupBy('host')
    |alert()
        .id('{{ .TaskName }} /{{ .Name }}/{{ .Group }}')
        .message('{{ .ID }} is {{ .Level }} ')
        .crit(lambda: "livecount" > 0)
        .stateChangesOnly()

It will query all the measurements start with "process_" which are used to monitor several  processes.
And each measurements have "host" as tag and "value" as field.

However When I enable this task, only one measurement get alert.
Is that supposed to be ? or there is another to handle this case ?

Thanks

**Comment by earthnut** [comment]
after I remove stateChangesOnly(), all the measurements get alert. But I need stateChangesOnly().

**Comment by nathanielc** [comment]
@earthnut Kapacitor doesn't have good support for query multiple measurements at once. It expects that the data be uniquely identified by its tags only not its measurement name. Since you have multiple processes on the same host, all the processes on a host are being treated as the same.

This is a bug and will need to be fixed. In the meantime is it possible to place the part of the process that matches the wildcard as a tag instead of a measurement name?

**Comment by earthnut** [comment]
@nathanielc  Thank for the reply.

I will try to do as you advised at this time.
