### ISSUE TITLE
x509: certificate signed by unknown authority For POST messages

### ISSUE THREAD

**Issue by fcastello** [influxdata/kapacitor#532]
I am getting this error

[cpu_alert:alert2] 2016/05/10 17:39:50 E! failed to POST batch Post https://user:pass@myurl/submit_result/: x509: certificate signed by unknown authority

I know the server needs some tweaking in the configuration but is it possible to skip ssl verification.

There is very little info about the post method in alert node. Some pointer will be helpful. 
Also can you point me in the code where the post is so I can look at it and understand what has been done

**Comment by nathanielc** [comment]
@fcastello Currently it is not possible to ignore SSL cert errors.

Code locations:

* Struct that defines available options: https://github.com/influxdata/kapacitor/blob/master/pipeline/alert.go#L397
* Method that posts the alert data:  https://github.com/influxdata/kapacitor/blob/master/alert.go#L742

> There is very little info about the post method in alert node.  

This is in part because it does very little.

**Comment by cryptokush** [comment]
tr := &http.Transport {
                TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
        }
        client := &http.Client{Transport: tr}
        _, err := client.Post(post.URL, "application/json", buf)

        if err != nil {
                a.logger.Println("E! failed to POST batch", err)
        }

quick hack, no config
