### ISSUE TITLE
Better handling of count alerts

### ISSUE THREAD

**Issue by lpalm** [influxdata/kapacitor#539]
A very common use case is to alert if the count of some event is higher than some threshold over a time window. For example, errors, timeouts, logins, requests. Currently we can simulate this by adding a point to InfluxDB with a meaningless value (e.g. 1) each time the event occurs. We can then compare the count of these values over a window and compare it against the alert threshold. We only use the **Batch** Kapacitor nodes, by the way.

The problem is, this doesn't work well if the count violates the threshold for one batch, then drops to zero, since we don't get the alert OK state because a batch with zero points is not emitted. If the next time the count goes over zero it also goes over the threshold, we'll miss the second alert. This gets more likely to occur as the event we're monitoring for becomes rarer. Obviously an alerting system has to work reliably for users to trust it, so we disabled (the frequently requested) alerting by count feature.

While I haven't tested this, I imagine similar issues would crop up if we used deadman's switch with group-by. E.g. how do we know to alert for some tag set if we haven't seen it before?.

I fully understand that InfluxDB may be reluctant to return counts of zero instead of not returning results, since it can't guess tag values for those empty points. But perhaps Kapacitor can overcome this limitation.

Below, I use the term "tag set" to refer to one specific combination of tag values.

### Non grouped by tag alerts
We can simply check if a batch has produced no points and infer a count of zero (or a NaN/error for other aggregations) for that batch. I don't mind if we keep emitting batches with a count of zero after the first one, since the main goal is to allow the alert to reset back to OK. 

### Grouped by tag alerts
For the group by case, we may not want to keep running and processing alerts for a steadily growing number of tag sets, so once the count for some tag set drops to zero we could only emit the next batch with a count of zero and not emit subsequent batches until we see another point (i.e. forget about that instance of the alert for that specific tag set). This should allow the alert to reset to OK and stop consuming resources. 
The same behavior could be achieved for the deadman functionality, with a caveat. We wouldn't be able to alert for low counts on tag sets that have never been seen before, but since the "normal" state is to have points being produced constantly (which is why we want to alert when we stop seeing them), this shouldn't be an issue in practice. Once we've seen at least one point for some tag set, we can emit a batch with a count of zero for it the next time we evaluate the batch, then forget about it until we see points for it again.

**Comment by nathanielc** [comment]
@lpalm Thanks for the detailed write up.

Currently the deadman switch works are you describe with one exception, that it will never forget a given tag set and will continue to emit 0 for it forever. I like the suggestion of dropping it after a single 0 has been emitted. 

Also in the case that the deadman's switch receives no points at all it will emit 0s for a `nil` tag set so that you know that nothing is being received.

Using example of errors this TICKscript should do what you want...

```go
batch
    |query(''' SELECT value FROM errors''')
       .period(1m)
       .every(1m)
    |deadman(0.0, 2m)
```

or if you need more control you can use the `stats` node directly which is what `deadman` uses under the hood.  https://docs.influxdata.com/kapacitor/v0.13/nodes/stats_node/
https://docs.influxdata.com/kapacitor/v0.13/nodes/query_node/#deadman

something like 

```go
batch
    |query(''' SELECT value FROM errors''')
       .period(1m)
       .every(1m)
     |stats(2m)
     |derivative('emitted')
            .unit(2m)
            .nonNegative()
     |alert()
         ...
```

I believe this will work as you expect, but if I have misunderstood please clarify.

**Comment by nathanielc** [comment]
@lpalm Also note that `|count` is not used explicitly since each point represents an event and the counting is being done implicitly via the `stats` node.

**Comment by lpalm** [comment]
Hi Nathaniel,

Thanks for the information. Sounds like deadman/StatsNode will do exactly what we'd like it to do for counts dropping below a threshold. But what about alerting if a count goes **above** a threshold (let's say, 10 in one minute), and making sure that it resets back to OK if the count drops to zero? 

And a tangential question about the use of nonNegative: If we take the derivative() (current - previous) and add .nonNegative(), doesn't that mean that we're [skipping negative derivatives](https://docs.influxdata.com/kapacitor/v0.13/nodes/derivative_node/#nonnegative) (i.e. when the 'emitted' value becomes smaller), and thus not alerting when the 'emitted' value drops below the threshold, since the derivative would always be negative when that happens?

**Comment by nathanielc** [comment]
Yes, nonNegative skips values where the derivative would be negative. But the emitted value is an increasing counter (total points emitted since task started), it never decreases. So the derivative will go to 0 but not negative.

**Comment by lpalm** [comment]
Got it. Thank you. My final outstanding question is if there is a way to alert the second time if some count goes above the threshold, drops to zero, then goes above the threshold again.

**Comment by nathanielc** [comment]
@lpalm It should alert the second time. Do you mean only alert if it happens twice?

**Comment by lpalm** [comment]
I was under the impression that for a batch with zero points, no window was emitted, so that we could miss alerts. E.g. Let's say we want to alert if the count goes above 5 and we have the following sequence of counts at each batch evaluation:

0 // No window emitted, OK
3 // Window emitted, below threshold, OK
6 // Above threshold, CRITICAL -> alert
0 // No window emitted, CRITICAL still, but no state change, so no alert
10 // Above threshold, but since we're still on critical, a second message isn't sent

Sounds like by using the stats node, we'll actually emit windows for the times we get zero datapoints and go back to the OK state on the fourth window above, allowing the fifth window to trigger the alert for a second time. I just wanted to confirm that this was the case.

**Comment by nathanielc** [comment]
@lpalm  Yes, you are correct. The stats node will emit the 0 and resolve the alert so that it will trigger a critical a second time.

Although you will run into a second problem, which is that the `emitted` value is the number of windows emitted not the number of points in the window. I have debated the usefulness of this and I think its time to change the emitted count for batch edges to be the number of points in the batch. I'll be playing around with this for a bit and let you know what I do.

**Comment by lpalm** [comment]
Much appreciated. Feel free to close this if you plan on letting me know in a different way. All my questions here are answered.

**Comment by nathanielc** [comment]
@lpalm  Thanks, see #605 for info on how the StatsNode will count batches. In short is being changed to be by number of points not number of  batches.

**Comment by sayan-rudder** [comment]
Querying over this thread as it seems to match my usecase.

Now, since the statsNode return the number of points. I am in a fix how it works with the queryNode's every and period property.

Like the example above where a batch is return every 1 min with the data of 1 min while the stats node emits data every 2 mins.

Is the flow something like
at t=0, the script started.
at t= 1m, the batch returned 'n' points from last 1m(period) influx data
at t= 2m, the batch returned 'm' points from last 1m influx data
stats node emits n+m points or n points only? since the query for influx data triggered by every at 2m in the timeline would take time to return ?

I an just starting up with tick stack. Sorry if I am thinking otherwise.
It would be helpful to get some idea behing every, period property and how stats node adds with it.

@nathanielc
