### ISSUE TITLE
Gracefully handle SIGPIPE

### ISSUE THREAD

**Issue by rossmcdonald** [influxdata/kapacitor#737]
Earlier versions of journald would send a SIGPIPE to any systemd processes when journald was restarted. So far we have bypassed this issue by redirecting STDOUT and STDERR to the traditional log paths, however in case users opt to use journald it would make sense to handle SIGPIPEs in a graceful manner to ensure the service doesn't crash when journald is restarted.

A similar fix was applied to Docker here: jwhonce/docker@b7f60f7

**Comment by nathanielc** [comment]
As per the linked patch, it looks like we just need to register a handler to ignore the SIGPIPE and that's it. Correct?

**Comment by nathanielc** [comment]
I have been reading up on this bug, here is my synposis and my conclusions

systemd version 218 or earlier has a bug where restarting journald causes SIGPIPE to be sent to the process since it can no longer write to STDOUT/STDERR. This means that the process has lost the ability to write logs to journald. In short, for these old versions of systemd restarting journald would cause the process to loose the ability to write anything to STDOUT/STDERR. 

Release notes for Go 1.6
> On Unix-like systems, when a write to os.Stdout or os.Stderr (more precisely, an os.File opened for file descriptor 1 or 2) fails due to a broken pipe error, the program will raise a SIGPIPE signal. By default this will cause the program to exit; this may be changed by calling the os/signal Notify function for syscall.SIGPIPE. A write to a broken pipe on a file descriptor other 1 or 2 will simply return syscall.EPIPE (possibly wrapped in os.PathError and/or os.SyscallError) to the caller. The old behavior of raising an uncatchable SIGPIPE signal after 10 consecutive writes to a broken pipe no longer occurs.

Now with Go 1.6 (the version Kapacitor uses), SIGPIPE is only sent to the process if a failure occurs on fd 1 or 2, (aka STDOUT and STDERR). This means that if Kapacitor receives a SIGPIPE its because it can no longer write to STDERR or STDOUT. In that case Kapacitor has lost the ability to log anything, and should shutdown.

 If you are not using STDOUT/STDERR for Kapacitor logs you will not get SIGPIPE and this issue is irrelevant. 

So we could setup a signal handler to safely shutdown Kapacitor, instead of letting it get terminated directly. Also we need to set an non zero exit code to indicate that the process failed, aka was forced to shutdown.

**Comment by nathanielc** [comment]
Nothing to do, closing.
