### ISSUE TITLE
last, sum, bottom, and other selectors one data point behind

### ISSUE THREAD

**Issue by phemmer** [influxdata/kapacitor#750]
When attempting to use selector methods such as `last`, the output value is missing the last data point.

For example:

```
stream|from().measurement('test')|last('val')|log()
```

Then run
```
influx -database telegraf <<'EOF'
insert test,host=foo val=0
insert test,host=foo val=1
EOF
```

Which outputs:
```
[test:log3] 2016/07/25 16:08:35 I!  {test    [] map[host:foo] map[last:0] 2016-07-25 20:08:33.87380073 +0000 UTC}
```

Subsequent inserts will always be one data point behind. Insert `val=2`, and the log will show `map[last:1]`

This doesn't seem like expected behavior. And if it is expected, I couldn't find anything in the docs which would explain why this happens.

**Comment by nathanielc** [comment]
@phemmer Last over what time period?

Since you are passing one data point at a time to the `last` call it is outputting only that data point. 

Using a `window` node to define the time period should provide the results you are looking for.


```go
stream
    |from()
        .measurement('test')
    |window()
        .period(1s)
        .every(1s)
    |last('val')
    |log()
```

Note: Last will work on a stream of points and will buffer up all points that have the exact same timestamp. In your example the timestamps for the two points are probably a few nanoseconds apart.

Another approach would be to truncate the precision of your streamed points this way:

```go
stream
    |from()
        .measurement('test')
        .truncate(1s)
    |last('val')
    |log()
```

But `last` is ordered by time, and then is undetermined for points that have the same time, so this approach is not ideal. But using `sum` or other aggregates would work.

**Comment by phemmer** [comment]
The data points can be minutes apart, and the issue still occurs.

Neither the `window()` or `.truncate()` had any impact on the behavior.

> Note: Last will work on a stream of points and will buffer up all points that have the exact same timestamp.

This would seem to explain the behavior. It's holding onto all metrics of the same timestamp, and only releases them once a new metric comes in with a different timestamp.
I'll close this as it would seem to be the expected behavior.
