### ISSUE TITLE
throughput always return 0

### ISSUE THREAD

**Issue by xuqingfeng** [influxdata/kapacitor#766]
version: `Kapacitor 0.13.1`

task info:
```
DOT:
digraph 579ac9c402ad1.memory.warning {
graph [throughput="0.00 points/s"];

stream0 [avg_exec_time_ns="0" ];
stream0 -> from1 [processed="22947"];

from1 [avg_exec_time_ns="3.277µs" ];
from1 -> window2 [processed="28"];

window2 [avg_exec_time_ns="1.068µs" ];
window2 -> mean3 [processed="2"];

mean3 [avg_exec_time_ns="0" ];
mean3 -> alert4 [processed="2"];

alert4 [alerts_triggered="2" avg_exec_time_ns="246.33989ms" crits_triggered="0" infos_triggered="0" oks_triggered="0" warns_triggered="2" ];
```

kapacitor is receving data from influxdb and do `alert` normally, but `throughput` always return 0.

**Comment by nathanielc** [comment]
@xuqingfeng This is a sampling issue. The throughput is measured once per second. If the task processes points less frequently than once per second then the measured throughput remains at zero.

For example if a task processes 100 points every 10s. Instead of the throughput getting averaged out to 10 points per second, it measures that no points were processed for a second and reports 0. On the tenth second it will report 100 then go back to zero for then rest of the time. Does that make sense? 

We should fix this so that the sampling doesn't cause these issues but currently any task that has lower processing frequency than 1 second will have an erroneous throughput value.

All that said you can still compute the throughput yourself using the internal Kapacitor statistics, if you need a real throughput value.

**Comment by xuqingfeng** [comment]
thanks for the clarify.
