### ISSUE TITLE
Error using field/tag from stream on UDF

### ISSUE THREAD

**Issue by siryur** [influxdata/kapacitor#767]
I'm trying to use a tag from a stream when calling my UDF.

```
var current = stream
    |from()
        .database('tabs')
        .retentionPolicy('default')
        .measurement('status')
        .where(lambda: "type" == 'load')
        .groupBy('space')
    |last('value')

current
    @test()
        .id("space") //space is a tag
        .timer("time") // time of the last value
```

My problem is:
On the UDF, when i'm trying to define the "timer" on the UDF if I use 
`"timer":        {ValueTypes: []udf.ValueType{udf.ValueType_INT}},`
when i'm defining the tick script i get this: 
> invalid TICKscript: line 23 char 10: unexpected arg to time, got BOOL expected INT

If I use
`"timer":        {ValueTypes: []udf.ValueType{udf.ValueType_INT}},`
when i define the tick script i get no error, but when I enable it, I get this, relative to the "space" tag:
> interface conversion: udf.isOptionValue_Value is nil, not *udf.OptionValue_BoolValue

So, I don't want it to load the "space" or the "time" on enabling the tick script (not understanding how I do this), also, I don't understand why "time" is a bool type ... 

Can any1 help me ?

**Comment by nathanielc** [comment]
@siryur I am not quite sure I understand what you are trying to do. If you are trying to get data off of the points themselves do that within the UDF code not in the TICKscript. The init options you pass to the UDF are during the UDF initialization step and cannot contain any data from the points. The properties are meant to be static args to your UDF.

But since the UDF is being passed the points, it is easy to get data from the points.  For example the time of the point or the value of the `space` tag.

Can you provide a little more detail as to what the `id` and `timer` properties are supposed to do? Then maybe I can suggest a more accurate solution.

Agreed the errors are misleading. We will fix them to be more clear.

**Comment by siryur** [comment]
I'm trying to calculate a value based on the time of the last inserted value of each space I have on "status" measurement.

So, my stream gives me the the last inserted value of each "space".

What I need for the formula:
- "time" of the last inserted row for the space
- value of the "space" (this space is a tag)

For example:
I have a file with a number `29` (this file is changed by another service). And I want to alert something (can be email, slack, etc...) based on: ("day of the week" + "hours of the day" - "space" * "value on file"). If this result is < 0 alert is triggered.

So, i want "time" and "space" to UDF, and I want to return a int

**Comment by nathanielc** [comment]
@siryur You don't need to specify what data get sent to the UDF. All the data for the points its receives is passed down to the UDF automatically.

**Comment by siryur** [comment]
ohhh I wasn't understanding what `*udf.Point` on `func (a *apiHandler) Point(p *udf.Point) error` was  :)
Thanks :D
