### ISSUE TITLE
Dependencies alerts

### ISSUE THREAD

**Issue by panda87** [influxdata/kapacitor#80]
In some alerts you want that more than one conditions will happen to issue an alert.

So the flow will be like the following, 
Query -> Alert -> Check N query -> Alert \ cancel the alert

What do you think?

**Comment by nathanielc** [comment]
Could you give a more concrete example of what you are trying to accomplish?

I think this can be solved using `join` but I am not sure.

**Comment by panda87** [comment]
For example, we I monitored CPU spike, I want to check the memory before I send the alert, if the memory is acting as expected, then I dont want to send the alert.

**Comment by nathanielc** [comment]
Would this work?

```
var cpu = stream.from('cpu')...
var mem = stream.from('mem')...

cpu.join(mem)
        .as('cpu', 'mem')
    .alert()
        .crit(lamda: "cpu.value" > 80 AND "mem.value" > 95)
         ....
```

**Comment by panda87** [comment]
This can be a good starting, if I take it further, I can think on a case that if I have CPU spike i'd want to see the last 5min avg cpu.
So it's also depends on time and not only on value and measurement.
Does this also supported, right?

**Comment by nathanielc** [comment]
Instead of thinking of action/reaction for alerting let's first define the criteria for the alert. For example lets choose something relatively complex.

* CPU -- There must be a spike in cpu over the last minute above 80% and the last 5 minutes of CPU must be over 70%
* Memory -- The last 5 minutes of memory usage must be above 80%

Ok now that we have our criteria we just need to figure out how to get those three data points into a single point so we can define our alert criteria.

Starting backwards here is our alerting criteria:

```
.alert()
    .crit(lambda: "cpu1min.mean" > 80 AND "cpu5min.mean" > 70 AND "mem5min.mean" > 80)
```

Ok so now we just need to define each of our fields and join on them. Since join uses time as the join index, we need to make sure that each stream is emitting a value at the same time. This is where the windowing functionality comes in.

```
var cpu1min = stream.from('cpu')
    .window()
        .period(1m)
        .every(1m)
        // align the window so that can we can ensure proper joining.
        .align()
    .mapReduce(influxql.mean('value'))

var cpu5min = stream.from('cpu')
    .window()
        .period(5m)
        //Note we still emit the value every minute so that we can join properly.
        .every(1m)
        .align()
    .mapReduce(influxql.mean('value'))

var mem5min = stream.from('mem')
    .window()
        .period(5m)
        //Note we still emit the value every minute so that we can join properly.
        .every(1m)
        .align()
    .mapReduce(influxql.mean('value'))

```

With that we have defined the three streams of fields we need. Now let's join them.

```
cpu1min.join(cpu5min, mem5min)
      .as('cpu1min', 'cpu5min', 'mem5min')
     // Now we have a stream of data with a value every minute that contains the cpu mean for the past 1 and 5 minutes as well as the mean memory usage for the past 5 minutes.
```

Putting it all together:

```
var cpu1min = stream.from('cpu')
    .window()
        .period(1m)
        .every(1m)
        // align the window so that can we can again ensure proper joining.
        .align()
    .mapReduce(influxql.mean('value'))

var cpu5min = stream.from('cpu')
    .window()
        .period(5m)
       //Note we still emit the value every minute so that we can join properly.
        .every(1m)
        .align()
    .mapReduce(influxql.mean('value'))

var mem5min = stream.from('mem')
    .window()
        .period(5m)
       //Note we still emit the value every minute so that we can join properly.
        .every(1m)
        .align()
    .mapReduce(influxql.mean('value'))

cpu1min.join(cpu5min, mem5min)
      .as('cpu1min', 'cpu5min', 'mem5min')
   .alert()
    .crit(lambda: "cpu1min.mean" > 80 AND "cpu5min.mean" > 70 AND "mem5min.mean" > 80)
```

**Comment by panda87** [comment]
@nathanielc Thanks for the described explanation, much appreciated!
