### ISSUE TITLE
combine does not add prefix to groupBy tags

### ISSUE THREAD

**Issue by phemmer** [influxdata/kapacitor#826]
Tick script:
```
stream
	| from().measurement('test').groupBy('bar')
	| combine(lambda: TRUE).as('mycombine')
	| log()

```

Test data:
```
insert test,bar=foo,pop=tart value=123i
```

Log output:
```
[test:log3] 2016/08/24 11:12:11 I!  {test   bar=foo {false [bar]} map[bar:foo mycombine.pop:tart] map[mycombine.value:123] 2016-08-24 15:12:06.268239798 +0000 UTC}
```

Notice that the `bar` tag is output as just `bar` instead of `mycombine.bar`

```
# kapacitor  version
Kapacitor 1.0.0~beta4 (git: master 1e00423551591862b11f70b5fc59a47300ef596c)
```

**Comment by nathanielc** [comment]
@phemmer This is expected as the tags will always be the same for all combined points since it is group by those tags. If the tag is expected to be different then don't group by it.

What are you trying to combine? Combining one point with itself does really do anything. Typically you are trying to combine multiple points into a single point.

**Comment by phemmer** [comment]
Fair enough. I just found it unexpected that all tags get a prefix except one. But the logic makes sense.
