### ISSUE TITLE
Cannot Force UDP port used for subscriptions

### ISSUE THREAD

**Issue by octalthorpe** [influxdata/kapacitor#848]
So I am running kapacaitor (actually multiple instances) in a docker container. For me not to run in host mode and allow multiple containers on a single piece of hardware I need to set the UPD port that the server will listen on and will set in the subscription, then I can expose this port in docker/ECS.  Unbounded dynamic port selection by applications in docker is a common issue we deal with all the time.

The config indicates that UDP port definition is possible but the code seem to disagree with that...
kapacitor.conf
```
# Host part of a bind addres for UDP listeners.
102	  # For example if a UDP listener is using port 1234
103	  # and `udp-bind = "hostname_or_ip"`,
…	
105	  # The default empty value will bind to all addresses.
106	  udp-bind = ""
```

service.go
```
case "udp":
				addr, err := s.startUDPListener(se, "0")
...
where the string "0" gets passed to StartUDPListner and 
c.BindAddress = fmt.Sprintf("%s:%s", s.udpBind, port)
...
```

The http protocol in code for subscriptions seems to allow for setting the port, but I fear for using that as the documentation does not really talk about any protocol selection.  Actually there is not much discussion at all about the subscription architecture, so I don't want to go down the path that either is not supported or gets deprecated.

I can see great benefit for using the HTTP/HTTPS protocol for subscriptions especially if you want to run kapacitor against a SAS, like "influx cloud" for instance, where the subscription stream might go across the public internets.

Is the HTTP protocol the way to go here? Is UDP port definition something that is supported and just was not implemented? Or am getting the code wrong?

Any feedback would be fantastic.
Thanks

**Comment by nathanielc** [comment]
@octalthorpe Good questions.

HTTP/HTTPS is the way to go. Its simpler to setup and a better transport mechanism in general. Using an Kapacitor version >= 1.0.0-beta1 will have HTTP subscription support.

The UDP port can be specified but not via the config. The `udp-bind` config option on'y effect the bind address(aka IP) but no the port. The reason is that there are multiple ports involved, one for each database retention policy pair. To configure them yourself you have to setup the subscriptions externally using the `CREATE SUBSCRIPTION ...` query. Then Kapacitor will use the ports defined in those subscriptions so long as they have the same name. But this is still difficult to automate and get right so I recommend using HTTP based subscriptions.

**Comment by octalthorpe** [comment]
Thanks, I will go down the http/https path.  Appreciate the guidance.
