### ISSUE TITLE
BigPanda support

### ISSUE THREAD

**Issue by rubycut** [influxdata/kapacitor#883]
Add support so that kapacitor can send alerts to BigPanda:

https://www.bigpanda.io/docs/display/BD/POST+alerts

Ideally, alerting though http POST should be expanded so that it is customisable.

**Comment by nathanielc** [comment]
@rubycut I'll mark this issue as help-wanted to see if someone from the community wants to take a stab at this.

> Ideally, alerting though http POST should be expanded so that it is customisable.

Since each of these services needs its own JSON format of the POST'ed data it seems hard to customize the POST handler as you would have to duplicate that work in each TICKscript and potentially need to include credentials directly in the TICKscript which isn't good.

It's not too difficult to add each of these services to Kapacitor, their are many example PRs #680 being a recent one.

**Comment by docmerlin** [comment]
closed in favor of #2304
