### ISSUE TITLE
Run Tasks on demand with external arguments

### ISSUE THREAD

**Issue by ConfiDev** [influxdata/kapacitor#968]
Our current system would receive data every few minutes, about every 15 min, once a day a big chunk ( data in 15 min granularity) and then there will be manual data insertions.
All of that data have to be downsampled to hourly and daily granularity with the addition of creating pre-calculated more or less complex statistics.

My current problem is, that I cannot create a batch tasks for either the daily nor manual insertion.
I cannot know beforehand, when the daily insertion is done.

I would like to be able to have tasks, which aren't scheduled regularly but can (only) be called manually on demand with arguments. So it would be comparable with stored procedures from SQL and the "exec" command.
I also cannot do it directly on the InfluxDB with queries because I would like to later use UDF which are just available in Kapacitor.

**Comment by nathanielc** [comment]
@ConfiDev If I understand correctly you want to process a chunk of data once it arrives, but you can't schedule a tasks since the data arrival time is unknown. I think the best option for you here will be the `replay-live` feature. It allows you to replay a set of data against task defined by certain time bounds. This can be called via the API or using the kapacitor CLI tool.

For example this command will replay the last days of data against the task:

```
$ kapacitor replay-live batch -task batch_task_name -rec-time -past 1d
```

Or you can replay specific ranges of time using the `-start` and `-stop` flags

```
$ kapacitor replay-live batch -task batch_task_name -rec-time -start '2016-10-13T00:00:00Z' -stop '2016-10-14T00:00:00Z'
```

Since it appears that this will need to be triggered manually it would not be hard to write small wrapper script around the CLI or call the API directly.

Here are the relevant API docs https://docs.influxdata.com/kapacitor/v1.0/api/api/#replay-data-without-recording 

 Hope that helps get you started.

**Comment by ConfiDev** [comment]
Awesome, that sounds just like what I need. Thanks for the tip.
